### ISSUE TITLE
Copilot: Sign In command has disappeared

### ISSUE THREAD

**Issue by pinturic** [TheSecEng/LSP-copilot#23]
After the change in the installation procedure (from subline package to git command) the "Copilot: Sign In" command has disappeared.

**Comment by jfcherng** [comment]
From what this conversation implies, I don't think you don't have to sign in when you have done it before.

**Comment by pinturic** [comment]
All the copilot seem to have disappeared.

**Comment by jfcherng** [comment]
I don't see why it's broken on your side, maybe try a manually git pull. If the problem persists, provide error messages in ST console.

**Comment by sexybiggetje** [comment]
I think I know why this is happening, as I don't get the Commands neither;
On my ST 4 (Build 4126 on Windows) I get the following errors in the console resulting in none of the commands being available;

> reloading python 3.3 plugin LSP-copilot.commands
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\<username>\AppData\Roaming\Sublime Text 3\Packages\LSP-copilot\commands.py", line 7, in <module>
    from LSP.plugin.core.registry import LspTextCommand, LspWindowCommand
ImportError: cannot import name LspWindowCommand
reloading python 3.3 plugin LSP-copilot.constants
reloading python 3.3 plugin LSP-copilot.listeners
reloading python 3.3 plugin LSP-copilot.plugin
reloading python 3.3 plugin LSP-copilot.types
reloading python 3.3 plugin LSP-copilot.utils

**Comment by jfcherng** [comment]
do you have LSP installed?

**Comment by sexybiggetje** [comment]
Yeah, I have multiple LSP plugins running within Sublime-LSP.

**Comment by jfcherng** [comment]
> Yeah, I have multiple LSP plugins running within Sublime-LSP.

OK. I can reproduce your case. Thanks.

**Comment by sexybiggetje** [comment]
I guess that LspWindowCommand was introduced *after* the last release (sublime-lsp 1.16.3, of June 18th). It was added in commit https://github.com/sublimelsp/LSP/commit/a579b9dc340c93c12a0ffeb8a2bccc04bd7f5b92 on July 6th.

**Comment by jfcherng** [comment]
> I guess that LspWindowCommand was introduced _after_ the last release (sublime-lsp 1.16.3, of June 18th). It was added in commit [sublimelsp/LSP@a579b9d](https://github.com/sublimelsp/LSP/commit/a579b9dc340c93c12a0ffeb8a2bccc04bd7f5b92) on July 6th.

yes, that's embarrassing...

**Comment by jfcherng** [comment]
@sexybiggetje please do a pull and restart ST to test the temporary fix.

**Comment by sexybiggetje** [comment]
I have pulled and restarted ST. I can confirm that the plugin is loading, but I still get no commands.
There's not much of interesting in the logs. I did open the settings file, yielding the following;

> git: using configuration from C:\Program Files\Git\cmd\git.exe
Unable to open /C/Users/username/AppData/Roaming/Sublime Text 3/Packages/User/LSP-copilot.sublime-settings
git: tracking working dir C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\LSP-copilot
❌ Copilot has NOT been signed in.
git: untracking working dir C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\LSP-copilot

**Comment by jfcherng** [comment]
> I have pulled and restarted ST. I can confirm that the plugin is loading, but I still get no commands. There's not much of interesting in the logs. I did open the settings file, yielding the following;
> 
> > git: using configuration from C:\Program Files\Git\cmd\git.exe
> > Unable to open /C/Users/username/AppData/Roaming/Sublime Text 3/Packages/User/LSP-copilot.sublime-settings
> > git: tracking working dir C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\LSP-copilot
> > ❌ Copilot has NOT been signed in.
> > git: untracking working dir C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\LSP-copilot

https://github.com/TheSecEng/LSP-copilot#setup

**Comment by sexybiggetje** [comment]
@jfcherng yes, I'm smart enough for that :-). However the issue is that the command palette doesn't show the sign in command. It only shows the settings file. Which is actually what this issue was about in the first place, the commands are missing. Just to be clear, the import error is gone after pulling.

This is how it looks when you open the command palette;

![image](https://user-images.githubusercontent.com/60222/180658391-21376dab-4580-4c7b-befe-4e39a99718fa.png)

**Comment by jfcherng** [comment]
Can't reproduce with clean portable ST 4126. I have no idea what's going on.

**Comment by jfcherng** [comment]
I seem able to reproduce it now... not sure why at this moment though.

**Comment by jfcherng** [comment]
OK. I know why... PHP has a base scope of `embedding.php`. It's neither `source` nor `text`... lol

@sexybiggetje  plz pull and restart.

**Comment by sexybiggetje** [comment]
Yeah, this solves the issue for me. I didn't realize that the sign in commands were language / scope dependant.
Thanks for your effort. I hope this solves it for @pinturic as well.

**Comment by pinturic** [comment]
yes it is working fantastic!!!
Thank you very much I really appreciate it.

**Comment by mobweb** [comment]
Should this be added to the README? The "Sign in" command did not show up for me and I was wondering why, until I found this issue: If there is no file open in ST, just the default "empty" file, the command will not show up. I had to open a PHP file for the command to show up.

**Comment by jfcherng** [comment]
> Should this be added to the README? The "Sign in" command did not show up for me and I was wondering why, until I found this issue: If there is no file open in ST, just the default "empty" file, the command will not show up. I had to open a PHP file for the command to show up.

@mobweb Thanks. Added.
