### ISSUE TITLE
And... how to sign in?

### ISSUE THREAD

**Issue by smileBeda** [TheSecEng/LSP-copilot#7]
I think this repos needs at least a readme for basic setup and usage.

For starters, the plugin needs the latest Node.js but note that Sublime text, if Node.JS is missing will not install the latests - rather 12.x version.
So that is something a readme could mention.

But most of all, after installing the plugin, it will not work because of `LSP-copilot] ⚠ Copilot has NOT been signed in.`
And there is no clear path as of how to sign in to Copilot.

It must be something in the setting of course, but that is rather unhelpful:
```
{
	"command": ["${node_bin}", "${server_path}", "--stdio"],
	"schemes": ["file", "buffer", "res"],
	"initializationOptions": {},
	"settings": {},
	// ST4 configuration
	"selector": "source | text",
}
```

It would be helpful for people to know how to make a basic setup, I think.

Thanks!

**Comment by jfcherng** [comment]
You can sign in via the command palette. https://github.com/TheSecEng/LSP-copilot/blob/ac4a8912f44a9fddd2dce548eb49bf666965b85f/Main.sublime-commands#L7

**Comment by smileBeda** [comment]
Thanks @jfcherng - that did that trick, now it throws a new error:
```
[LSP-copilot] ✈ Copilot has been signed in.
failed to register session LSP-copilot to listener ViewListener(62)
Traceback (most recent call last):
  File ".../Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 184, in _publish_sessions_to_listener_async
    listener.on_session_initialized_async(session)
  File ".../Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/documents.py", line 218, in on_session_initialized_async
    self._session_views[session.config.name] = SessionView(self, session, self._uri)
  File ".../Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/session_view.py", line 53, in __init__
    session_buffer = SessionBuffer(self, buffer_id, uri)
  File ".../Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/session_buffer.py", line 113, in __init__
    self._check_did_open(view)
  File ".../Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/session_buffer.py", line 142, in _check_did_open
    self.session.send_notification(did_open(view, language_id))
  File ".../Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/views.py", line 387, in did_open
    return Notification.didOpen(did_open_text_document_params(view, language_id))
  File ".../Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/views.py", line 340, in did_open_text_document_params
    return {"textDocument": text_document_item(view, language_id)}
  File ".../Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/views.py", line 315, in text_document_item
    "uri": uri_from_view(view),
  File ".../Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/views.py", line 283, in uri_from_view
    raise MissingUriError(view.id())
LSP.plugin.core.views.MissingUriError: View 62 has no URI
```

This seems to be due to some configuration missing, but I wouldn't know what?

**Comment by jfcherng** [comment]
If you are using ST 3, I don't think we support it.

**Comment by smileBeda** [comment]
Actually I got it working now.
Well, apart of PHP files, lol - which is the one I'd use it for.

ST 4?
I do not get any notification of any update :(

Thanks!

**Comment by jfcherng** [comment]
> ST 4?
> I do not get any notification of any update :(

It has been more than one year since it's publicly announced. Some new plugins only target on ST 4 given its new Python 3.8 bindings and new features/APIs.

---

Closed as resolved.

**Comment by jfcherng** [comment]
> Not sure why the log above would say I use ST 3

That means you migrate from ST 3. Without BC break, ST 4 has to look for ST 3's setting directory as a fallback if `.../Library/Application Support/Sublime Text` doesn't exist. You can manually rename it if you don't use ST 3 anymore.
