### ISSUE TITLE
Not working at all?

### ISSUE THREAD

**Issue by marimeireles** [TheSecEng/LSP-copilot#93]
I can only access the settings of the addon, nothing else works for me.
The login command doesn't do anything to me. Not sure how to check my version but I've just downloaded it.
I'm running it on an osx.
Cheers!

**Comment by jfcherng** [comment]
> The login command doesn't do anything to me. 

What does this mean? You can see the sign-in command, you execute it and nothing happen?

**Comment by jfcherng** [comment]
the very first step is open a file.

**Comment by marimeireles** [comment]
I see, thanks for chiming in @neverbot, I'll try again. I've restarted sublime and it didn't work. Same as @neverbot described.

**Comment by jfcherng** [comment]
If you see the readme, the first step is OPEN A FILE. NOT searching with "copilot".

**Comment by mobweb** [comment]
Also worth noting that it may only work when a file of a certain type is opened. Personally I had to have a PHP file open, other file types (don't remember which ones, might've been TXT) did not cause the expected command to appear.

**Comment by jfcherng** [comment]
LSP-copilot should work on all files, literally.

**Comment by bwalkernz** [comment]
After installation, restarting and opening a file, I can see "co pilot not signed in" in the status bar when I first open a file. But then I cannot find "Copilot: Sign In"  in the command palette?? "LSP-Co" It then changes to "LSP-copilot" in the status bar.
![Screen Shot 2023-03-24 at 2 24 36 PM](https://user-images.githubusercontent.com/6212854/227400652-7121b49e-021c-4bf4-86aa-d8cdbf7111e0.png)

**Comment by TerminalFi** [comment]
> After installation, restarting and opening a file, I can see "co pilot not signed in" in the status bar when I first open a file. But then I cannot find "Copilot: Sign In"  in the command palette??  It then changes to "LSP-copilot" in the status bar.
> 
> ![Screen Shot 2023-03-24 at 2 24 36 PM](https://user-images.githubusercontent.com/6212854/227400652-7121b49e-021c-4bf4-86aa-d8cdbf7111e0.png)
> 
> 

Is there a LSP: Check Status ?

**Comment by bwalkernz** [comment]
> > After installation, restarting and opening a file, I can see "co pilot not signed in" in the status bar when I first open a file. But then I cannot find "Copilot: Sign In"  in the command palette??  It then changes to "LSP-copilot" in the status bar.
> > ![Screen Shot 2023-03-24 at 2 24 36 PM](https://user-images.githubusercontent.com/6212854/227400652-7121b49e-021c-4bf4-86aa-d8cdbf7111e0.png)
> 
> Is there a LSP: Check Status ?

No

**Comment by jfcherng** [comment]
Fwiw, it's `Copilot: Check Status`.

**Comment by bwalkernz** [comment]
> Copilot: Check Status

this is not there either.

**Comment by jfcherng** [comment]
Having no idea what's happening as I don't think that's possible.

**Comment by jfcherng** [comment]
Can you run `LSP: Troubleshoot Server`?

**Comment by bwalkernz** [comment]
> LSP: Troubleshoot Server

Yes that worked

# Troubleshooting: LSP-copilot
## Version
 - LSP: 1.23.0
 - Sublime Text: 4143
## Server Test Run
 - exit code: 0
 - output
```

```
## Server Configuration
 - command
```json
[
  "${node_bin}", 
  "${server_path}", 
  "--stdio"
]
```
 - shell command
```sh
/usr/local/bin/node "/Users/pod71/Library/Caches/Sublime Text 3/Package Storage/LSP-copilot/16.14.0/language-server/node_modules/copilot-node-server/copilot/dist/agent.js" --stdio
```
 - selector
```
source | text | embedding
```
 - priority_selector
```
source | text | embedding
```
 - init_options
```json
{}
```
 - settings
```json
{
  "auto_ask_completions": true, 
  "completion_style": "popup", 
  "debug": false, 
  "hook_to_auto_complete_command": false, 
  "local_checks": false, 
  "proxy": "", 
  "telemetry": false
}
```
 - env
```json
{
  "PATH": "/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:/usr/local/bin:"
}
```

## Active view
 - File name
```
/Users/pod71/sites/te-kaha-2022/components/Footer.js
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": true, 
  "syntax": "Packages/Babel/JavaScript (Babel).sublime-syntax"
}
```
 - base scope
```
source.js
```

## Project / Workspace
 - folders
```json
[
  "/Users/pod71/sites/te-kaha-2022"
]
```
 - is project: False

## LSP configuration

<not found>
## System PATH
 - /opt/homebrew/bin
 - /opt/homebrew/sbin
 - /usr/local/bin
 - /usr/bin
 - /bin
 - /usr/sbin
 - /sbin
 - /Library/Apple/usr/bin

**Comment by jfcherng** [comment]
Is there any error message in ST's console? (`` ctrl+ ` ``)

**Comment by bwalkernz** [comment]
> Is there any error message in ST's console? (`` ctrl+ ` ``)

git: using configuration from system git install
git: tracking working dir /Users/pod71/sites/te-kaha-2022
❌ Copilot has NOT been signed in.
Unable to open /Users/pod71/Library/Application Support/Sublime Text 3/Packages/LSP/LSP.sublime-settings
Unable to open /Users/pod71/Library/Application Support/Sublime Text 3/Packages/User/LSP.sublime-settings
❌ Copilot has NOT been signed in.
Unable to open /Users/pod71/Library/Application Support/Sublime Text 3/Packages/LSP-copilot/LSP-copilot.sublime-settings
Unable to open /Users/pod71/Library/Application Support/Sublime Text 3/Packages/User/LSP-copilot.sublime-settings
❌ Copilot has NOT been signed in.
Unable to open /Users/pod71/Library/Application Support/Sublime Text 3/Packages/LSP-copilot/LSP-copilot.sublime-settings
Unable to open /Users/pod71/Library/Application Support/Sublime Text 3/Packages/User/LSP-copilot.sublime-settings
❌ Copilot has NOT been signed in.
Unable to open /Users/pod71/Library/Application Support/Sublime Text 3/Packages/Package Control/Package Control.sublime-settings
❌ Copilot has NOT been signed in.
no command for selector: noop:
no command for selector: noop:

**Comment by bwalkernz** [comment]
> ```
> Unable to open /Users/pod71/Library/Application Support/Sublime Text 3/Packages/LSP-copilot/LSP-copilot.sublime-settings
> Unable to open /Users/pod71/Library/Application Support/Sublime Text 3/Packages/User/LSP-copilot.sublime-settings
> ```
> 
> Does these happen even if you restart ST?

I get these

plugins loaded
Failed to register plugin "LSP-copilot-master"
Traceback (most recent call last):
  File "/Users/pod71/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 997, in _register_plugin_impl
    if client_configs.add_external_config(name, settings, base_file, notify_listener):
  File "/Users/pod71/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/settings.py", line 35, in add_external_config
    config = ClientConfig.from_sublime_settings(name, s, file)
  File "/Users/pod71/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/types.py", line 682, in from_sublime_settings
    base = sublime.decode_value(sublime.load_resource(file))
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 436, in load_resource
    raise IOError('resource "%s" not found' % name)
OSError: resource "Packages/LSP-copilot-master/LSP-copilot-master.sublime-settings" not found

Failed to register plugin "LSP-copilot-master"
Traceback (most recent call last):
  File "/Users/pod71/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 997, in _register_plugin_impl
    if client_configs.add_external_config(name, settings, base_file, notify_listener):
  File "/Users/pod71/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/settings.py", line 35, in add_external_config
    config = ClientConfig.from_sublime_settings(name, s, file)
  File "/Users/pod71/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/types.py", line 682, in from_sublime_settings
    base = sublime.decode_value(sublime.load_resource(file))
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 436, in load_resource
    raise IOError('resource "%s" not found' % name)
OSError: resource "Packages/LSP-copilot-master/LSP-copilot-master.sublime-settings" not found

❌ Copilot has NOT been signed in.
Package Control: No updated packages

**Comment by jfcherng** [comment]
> Failed to register plugin "LSP-copilot-master"

So, it looks like you didn't installed this plugin with Package Control.

**Comment by bwalkernz** [comment]
> > Failed to register plugin "LSP-copilot-master"
> 
> So, it looks like you didn't installed this plugin with Package Control (?). But this is not the case in your previous report. I am confused by the situation now. Please remove `Packages/LSP-copilot-master` directory and restart ST.

this worked thank you.

**Comment by jfcherng** [comment]
For people who are still suffering here, providing the output of following steps may help people to help you.

1. After open a real file on your filesystem, is there `LSP-copilot` at the bottom-left of the ST window?
2. What's the output of `Copilot: Check Status` from the command palette?
3. What's the output of `LSP: Troubleshoot Server` from the command palette?
4. Is there any error message in ST's console? (`` Ctrl+` ``)

**Comment by tomohiro-sawada** [comment]
Hello. I have the same issue. 

> 1. After open a real file on your filesystem, is there LSP-copilot at the bottom-left of the ST window?
Yes, I get "LSP-copilot" at the bottom left of the screen when I open a php file. 

<img width="402" alt="Screenshot 2023-04-04 at 23 48 11" src="https://user-images.githubusercontent.com/103265438/229976409-7236e877-080f-4be0-83ba-f9131f197749.png">

> 2. What's the output of Copilot: Check Status from the command palette?

I get back "[LSP-copilot] You haven't signed in yet."

> 3. What's the output of LSP: Troubleshoot Server from the command palette?

# Troubleshooting: LSP-copilot
## Version
 - LSP: 1.23.0
 - Sublime Text: 4143
## Server Test Run
 - exit code: 0
 - output
```

```
## Server Configuration
 - command
```json
[
  "${node_bin}", 
  "${server_path}", 
  "--stdio"
]
```
 - shell command
```sh
/usr/local/bin/node "/Users/tomohirosawada/Library/Caches/Sublime Text 3/Package Storage/LSP-copilot/16.13.1/language-server/node_modules/copilot-node-server/copilot/dist/agent.js" --stdio
```
 - selector
```
source | text | embedding
```
 - priority_selector
```
source | text | embedding
```
 - init_options
```json
{}
```
 - settings
```json
{
  "auto_ask_completions": true, 
  "completion_style": "popup", 
  "debug": false, 
  "hook_to_auto_complete_command": false, 
  "local_checks": false, 
  "proxy": "", 
  "telemetry": false
}
```
 - env
```json
{
  "PATH": "/usr/local/bin:/usr/local/bin:"
}
```

## Active view
 - File name
```
/Users/tomohirosawada/Desktop/sample.php
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": true, 
  "syntax": "Packages/PHP/PHP.sublime-syntax"
}
```
 - base scope
```
embedding.php
```

## Project / Workspace
 - folders
```json
[]
```
 - is project: False

## LSP configuration

<not found>
## System PATH
 - /Library/Frameworks/Python.framework/Versions/2.7/bin
 - /Library/Frameworks/Python.framework/Versions/3.9/bin
 - /Library/Frameworks/Python.framework/Versions/3.10/bin
 - /opt/local/bin
 - /opt/local/sbin
 - /usr/local/bin
 - /usr/bin
 - /bin
 - /usr/sbin
 - /sbin
 - /Library/TeX/texbin
 - /Library/Apple/usr/bin

> 4. Is there any error message in ST's console? (Ctrl+`)

Package Control: Skipping automatic upgrade, last run at 2023-04-04 23:17:47, next run at 2023-04-05 00:17:47 or after
ignored packages updated to: ["LSP-copilot", "RichTextFormat", "Vintage"]
unloading python 3.3 plugin LSP-copilot.boot
reloading settings Packages/LSP-copilot/LSP-copilot.sublime-settings
reloading settings Packages/LSP-copilot/LSP-copilot.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
error: Error trying to load settings: Settings must be a json object in Packages/LSP-copilot/LSP-copilot.sublime-settings
Package Control: The package LSP-copilot has been removed
reloading settings Packages/User/Package Control.sublime-settings
Package Control: The orphaned dependency lsp_utils has been removed
ignored packages updated to: ["0_package_control_loader", "LSP-copilot", "RichTextFormat", "Vintage"]
unloading python 3.3 plugin 0_package_control_loader.00-package_control
unloading python 3.3 plugin 0_package_control_loader.01-pygments
unloading python 3.3 plugin 0_package_control_loader.01-sublime_lib
unloading python 3.3 plugin 0_package_control_loader.10-lsp_utils
unloading python 3.3 plugin 0_package_control_loader.50-backrefs
unloading python 3.3 plugin 0_package_control_loader.50-bracex
unloading python 3.3 plugin 0_package_control_loader.50-markupsafe
unloading python 3.3 plugin 0_package_control_loader.50-pathlib
unloading python 3.3 plugin 0_package_control_loader.50-python-markdown
unloading python 3.3 plugin 0_package_control_loader.50-pyyaml
unloading python 3.3 plugin 0_package_control_loader.51-python-jinja2
unloading python 3.3 plugin 0_package_control_loader.55-mdpopups
unloading python 3.3 plugin 0_package_control_loader.55-wcmatch
Package Control: The orphaned dependency sublime_lib has been removed
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["0_package_control_loader", "RichTextFormat", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
generating syntax summary
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["RichTextFormat", "Vintage"]
reloading python 3.3 plugin 0_package_control_loader.00-package_control
reloading python 3.3 plugin 0_package_control_loader.01-pygments
reloading python 3.3 plugin 0_package_control_loader.50-backrefs
reloading python 3.3 plugin 0_package_control_loader.50-bracex
reloading python 3.3 plugin 0_package_control_loader.50-markupsafe
reloading python 3.3 plugin 0_package_control_loader.50-pathlib
reloading python 3.3 plugin 0_package_control_loader.50-python-markdown
reloading python 3.3 plugin 0_package_control_loader.50-pyyaml
reloading python 3.3 plugin 0_package_control_loader.51-python-jinja2
reloading python 3.3 plugin 0_package_control_loader.55-mdpopups
reloading python 3.3 plugin 0_package_control_loader.55-wcmatch
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["LSP-copilot", "RichTextFormat", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: The dependency 'lsp_utils' is not currently installed; installing...
Package Control: The dependency 'lsp_utils' has successfully been installed or updated
Package Control: The dependency 'sublime_lib' is not currently installed; installing...
Package Control: The dependency 'sublime_lib' has successfully been installed or updated
reloading settings Packages/User/Package Control.sublime-settings
generating syntax summary
ignored packages updated to: ["RichTextFormat", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/LSP-copilot/LSP-copilot.sublime-settings
reloading python 3.3 plugin LSP-copilot.boot
reloading settings Packages/User/Preferences.sublime-settings
[lsp_utils] START output of command: "ci --omit=dev --scripts-prepend-node-path=true --verbose"
npm verb cli /usr/local/bin/node /usr/local/bin/npm
npm info using npm@9.5.1
npm info using node@v16.13.1
npm verb title npm ci
npm verb argv "ci" "--omit" "dev" "--scripts-prepend-node-path" "true" "--loglevel" "verbose"
npm verb logfile logs-max:10 dir:/Users/tomohirosawada/.npm/_logs/2023-04-05T04_02_13_900Z-
npm verb logfile /Users/tomohirosawada/.npm/_logs/2023-04-05T04_02_13_900Z-debug-0.log
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 351ms
npm http fetch GET 200 https://registry.npmjs.org/npm 439ms (cache updated)

added 1 package, and audited 2 packages in 608ms

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.6.3
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.3>
npm notice Run `npm install -g npm@9.6.3` to update!
npm notice 
npm verb exit 0
npm info ok
[lsp_utils] Command output END
❌ Copilot has NOT been signed in.

**Comment by jfcherng** [comment]
Hi @tomohiro-sawada , do you mean there is no `Copilot: Sign In` in the command palette for you?

**Comment by tomohiro-sawada** [comment]
That's not it. I have `Copilot: Sign In` in the command palette when I open
a .php file, and a login window pops up in my browser. However, even if I
fill out the confirmation code, Sublime Text still says that I am not
logged in.

**Comment by jfcherng** [comment]
After you fill out the confirmation code and back to ST to "Press OK when completed.", there should be another popup message box. What it says?

**Comment by tomohiro-sawada** [comment]
I don't get a popup message box in Sublime Text after I press ok.



[image: Screenshot 2023-04-05 at 13.43.58.png][image: Screenshot 2023-04-05
at 13.44.05.png][image: Screenshot 2023-04-05 at 13.44.12.png][image:
Screenshot 2023-04-05 at 13.44.19.png][image: Screenshot 2023-04-05 at
13.44.54.png]

**Comment by jfcherng** [comment]
> I don't get a popup message box in Sublime Text after I press ok.

If so, any error in the console or LSP's log panel?

**Comment by jfcherng** [comment]
OK. So this is it, it failed to write into 
![image](https://user-images.githubusercontent.com/6594915/230162567-fc53860c-8b6d-4d04-9729-e6128655ba4d.png)

**Comment by tomohiro-sawada** [comment]
That's right.

**Comment by jfcherng** [comment]
Check the permission for sure. Or just `chmod u+rw` on that file.

**Comment by tomohiro-sawada** [comment]
> Check the permission for sure. Or just `chmod u+rw` on that file. Or maybe something in the upper-level folder's permission gets wrong. Or maybe the file owner is wrong.

Yes! That did the trick! Thank you very much!

**Comment by shjohnson** [comment]
Just wanted to add that i had a lot of the above problems and was only opening a file straight from terminal and wasnt working. I had to open a file through sublime (as mentioned i know 😞 ) to get things working in case someone else has this issue.

**Comment by MillhioreBT** [comment]
It had been a while since I last checked the repository since the time I asked if Copilot for ST existed. I have been experiencing this issue occasionally and it is very annoying, so I came to check if anyone else was experiencing it and yes, I can see that some are.

I suppose this is more related to LSP, although it's strange that LSP-lua doesn't have this issue...

**Comment by jfcherng** [comment]
Unfortunately, I just kind of never have this issue. It just work...

**Comment by chustedde** [comment]
I had issues similar to the ones above, where `Copilot: Check Status` wasn't showing up for me in the Command Palette after restarting ST4 and opening a real file.

In my case, I saw errors in the console when using the commands `Preferences: LSP Settings` and `Preferences: Lsp-copilot Settings` .

In both cases, ST4 was unable to find the settings files. Steps to resolve:

* Created folders `LSP` and `LSP-Copilot` under `C:\Users\<username>\AppData\Roaming\Sublime Text\Packages`
* Saved the files that came up for the general settings in the respective folders
* Saved the files that came up for user settings under `C:\Users\<username>\AppData\Roaming\Sublime Text\Packages\User`
* Closed ST4 and reopened
* Followed the rest of the steps from the Readme and they were successful this time

**Comment by jfcherng** [comment]
> * Created folders `LSP` and `LSP-Copilot` under `C:\Users\<username>\AppData\Roaming\Sublime Text\Packages`

We recommend people installing this Package with Package Control.

**Comment by chustedde** [comment]
> > * Created folders `LSP` and `LSP-Copilot` under `C:\Users\<username>\AppData\Roaming\Sublime Text\Packages`
> > * Saved the files that came up for the general settings in the respective folders
> > * Saved the files that came up for user settings under `C:\Users\<username>\AppData\Roaming\Sublime Text\Packages\User`
> 
> We recommend people installing this Package with Package Control.

I installed via Package Control and still ran into this issue.

**Comment by jfcherng** [comment]
> I installed via Package Control and still ran into this issue.

See https://github.com/TerminalFi/LSP-copilot/issues/93#issuecomment-1482176562

**Comment by chustedde** [comment]
> > I installed via Package Control and still ran into this issue.
> 
> See [#93 (comment)](https://github.com/TerminalFi/LSP-copilot/issues/93#issuecomment-1470131102)

Yes, that's actually the comment that helped me! I commented with the steps to resolve my situation, in case it helps others with similar issues with ST4 on Win11 who see this. I'm able to use the plugin now, I was just trying to potentially help others who also come across this issue, and document a case that was slightly different from others above.

**Comment by isokosan** [comment]
With a fresh install of sublime text 4 on Ubuntu 22 and installing LSP-Copilot via the Package Manager, I am also running into this issue. Where LSP-Copilot does not even appear on the bottom left, no matter what type of file I open and how many times I restart ST4.

In the console output I get the error no package LSP:
```

Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/deniz/.config/sublime-text/Installed Packages/LSP-copilot.sublime-package/boot.py", line 12, in <module>
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/deniz/.config/sublime-text/Installed Packages/LSP-copilot.sublime-package/plugin/__init__.py", line 1, in <module>
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1692, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/home/deniz/.config/sublime-text/Installed Packages/LSP-copilot.sublime-package/plugin/commands.py", line 5, in <module>
ImportError: No module named 'LSP'
```

**Comment by cqc-alec** [comment]
Had the same issue. Solved by restarting Sublime Text a second time. (I had already restarted it once as per the instructions.) There was also an LSP update at the same time; maybe that had something to do with it.
